### ISSUE TITLE
torch.compile + self.log() breaks on PyTorch 2.12 / 2.13 (InternalTorchDynamoError on getfullargspec)

### ISSUE THREAD

**Issue by bhimrazy** [Lightning-AI/pytorch-lightning#21836]
## Bug description

Training a `torch.compile`d `LightningModule` that calls `self.log()` in its `training_step` fails on PyTorch 2.12 and 2.13. It works fine on PyTorch 2.11 and earlier.

```
torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__'
```

### What's happening

Inside `self.log()`, Lightning checks whether `training_step` declares a `dataloader_iter` argument using [`is_param_in_hook_signature`](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/utilities/signature_utils.py), which calls `inspect.getfullargspec(self.training_step)`.

On a compiled model, `training_step` is a Dynamo-wrapped bound method (we rebind the step methods in [`compile.py`](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/utilities/compile.py)), and tracing that signature introspection is what crashes.

The root cause is in PyTorch's Dynamo: `getfullargspec` on a bound method ends up calling `object.__getattribute__(value, "__dict__")` in `torch/_dynamo/variables/dicts.py`, but `method` objects have no `__dict__`. On 2.11 Dynamo simply graph-broke on `inspect` instead of tracing into it, so the introspection ran eagerly and this never surfaced.

- Upstream PyTorch issue: https://github.com/pytorch/pytorch/issues/190171
- First seen in CI on the 2.12 job (`test_trainer_compiled_model_that_logs`): https://github.com/Lightning-AI/pytorch-lightning/actions/runs/29397385484/job/87294150264

## What version are you seeing the problem on?

`master` — surfaces once PyTorch 2.12 / 2.13 are added to the CI matrix.

## How to reproduce the bug

```python
import torch
from lightning.pytorch import Trainer
from lightning.pytorch.demos.boring_classes import BoringModel


class MyModel(BoringModel):
    def training_step(self, batch, batch_idx):
        loss = self.step(batch)
        self.log("loss", loss)
        return loss


model = torch.compile(MyModel())
trainer = Trainer(
    fast_dev_run=True,
    enable_checkpointing=False,
    enable_model_summary=False,
    enable_progress_bar=False,
    accelerator="cpu",
)
trainer.fit(model)
```

## Error messages and logs

```
  File ".../lightning/pytorch/core/module.py", line 514, in log
    and is_param_in_hook_signature(self.training_step, "dataloader_iter", explicit=True)
  File ".../lightning/pytorch/utilities/signature_utils.py", line 31, in is_param_in_hook_signature
    parameters = inspect.getfullargspec(hook_fx)
  ...
torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__'
```

## Environment

<details>
  <summary>Current environment</summary>

```
* PyTorch Lightning Version: master
* PyTorch Version: 2.12 / 2.13
* Python version: 3.12
* OS: Linux (also reproduces on macOS)
* How you installed Lightning: pip / source
```

</details>

## More info

Logging is a side effect that must run eagerly, so there's nothing to gain from tracing it. The fix is to disable compile tracing at the logging boundary (`@torch.compiler.disable` on `LightningModule.log`), which matches how `_ResultCollection.log` and `toggle_optimizer` are already handled.
