### ISSUE TITLE
flop_counts missing for deepspeed in 2.5.5

### ISSUE THREAD

**Issue by bnestor** [Lightning-AI/pytorch-lightning#21231]
### Bug description

There is no `flop_counts` in version 2.5.5
https://github.com/Lightning-AI/pytorch-lightning/blob/dd0a8f3c6a2cd6b6e3f63f52e73692b5f5b7e6bd/src/lightning/pytorch/utilities/model_summary/model_summary.py#L148

It does exist in the main branch:
https://github.com/Lightning-AI/pytorch-lightning/blob/e088694d411790747af1a52a59a20e6efaa1bebd/src/lightning/pytorch/utilities/model_summary/model_summary.py#L314

commenting out this line: 
https://github.com/Lightning-AI/pytorch-lightning/blob/dd0a8f3c6a2cd6b6e3f63f52e73692b5f5b7e6bd/src/lightning/pytorch/utilities/model_summary/model_summary_deepspeed.py#L102
allows it to work

### What version are you seeing the problem on?

v2.5

### How to reproduce the bug

```python
dataloader = DataLoader(my_dataset)
ptl_model = AnyModel()

trainer = Trainer(accelerator="auto", strategy="deepspeed_stage_3")

trainer.fit(ptl_model, dataloader)
```

### Error messages and logs

```
Traceback (most recent call last):
  File "myfile.py", line 373, in main
    trainer.fit(ptl_model, training_dataloader, validation_dataloader)
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 560, in fit
    call._call_and_handle_interrupt(
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 598, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 991, in _run
    call._call_callback_hooks(self, "on_fit_start")
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 228, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_summary.py", line 65, in on_fit_start
    summary_data = model_summary._get_summary_data()
  File "envs/torch/lib/python3.10/site-packages/pytorch_lightning/utilities/model_summary/model_summary_deepspeed.py", line 102, in _get_summary_data
    ("FLOPs", list(map(get_human_readable_count, (sum(x.values()) for x in self.flop_counts.values())))),
AttributeError: 'DeepSpeedSummary' object has no attribute 'flop_counts'

```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.5.0): 2.5.5
#- PyTorch Version (e.g., 2.5): 2.8.0
#- Python version (e.g., 3.12): 3.10
#- OS (e.g., Linux): linux
#- CUDA/cuDNN version: 12.6
#- GPU models and configuration: Nvidia rtx series
#- How you installed Lightning(`conda`, `pip`, source): pip install pytorch-lightning
```

</details>

**Comment by deependujha** [comment]
Hi @bnestor, thanks for reporting this. I was able to reproduce the error on **Lightning v2.5.5**.

### Workaround

✅ As a temporary fix, `installing Lightning from source (master branch) resolves the issue` since the missing code is present there.

### Root cause

* FLOP support in the model summary was introduced in [PR #20868](https://github.com/Lightning-AI/pytorch-lightning/pull/20868/files#diff-181fd36c25ca3c17bd03d98b15d254cdc4dc0c5c231c32a98586d14d73163fa6R298).
* FLOP information for the DeepSpeed summary was later added in [PR #21100](https://github.com/Lightning-AI/pytorch-lightning/pull/21100/files#diff-6c93b2810f1f10da6c9ae8cdb84a1f950973da14da7e9cf8494c8ad10bfa8684R102).
* However, the 2.5.2 release (`June 20`) and subsequent 2.5.5 do not include #20868, even though it was already merged into main by then. This leaves DeepSpeedSummary referencing flop_counts without the method defined, leading to the AttributeError.

### Next step

It looks like the release branch did not pick up #20868 before the 2.5.x releases were cut. A patch release that includes #20868  should fix this for PyPI users.

compare changes: https://github.com/Lightning-AI/pytorch-lightning/compare/2.5.1...2.5.2


cc: @Borda @SkafteNicki

**Comment by SkafteNicki** [comment]
Either we go for a patch release or maybe it is time for a minor release to make sure that newest release is in full sync with master?

**Comment by deependujha** [comment]
Yeah, a minor release makes more sense to get `master` fully in sync.

**Comment by GdoongMathew** [comment]
Because of the BC change introduced in #20868, a minor version update would make more sense.

**Comment by LckyLke** [comment]
any updates on the PyPI release?

**Comment by deependujha** [comment]
@LckyLke, we made a release yesterday. can you please check?

cc: @justusschock

**Comment by LckyLke** [comment]
```
[rank0]: AttributeError: 'DeepSpeedSummary' object has no attribute 'flop_counts'
(dice) [lukef@luke dice-embeddings]$ python
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightning
>>> lightning.__version__
'2.5.6'
```

not fixed yet on 2.5.6

**Comment by LckyLke** [comment]
Which branch was the released based on? Because master branch is working perfectly fine :-)

**Comment by deependujha** [comment]
Hi @LckyLke, We will probably do 2.6.0 early next week from master, which is expected to fix this issue.

**Comment by GdoongMathew** [comment]
Hi @bnestor and @LckyLke, [lightning 2.6.0](https://github.com/Lightning-AI/pytorch-lightning/releases/tag/2.6.0) has just been released, which should include the related fixes. Please let us know if the problem persists. 
Thanks~

**Comment by SkafteNicki** [comment]
Closing issue due to release of lightning 2.6.0.
